### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by Tygra** [CoderCow/Protector-Plugin#30]
Hey CoderCow,

First of all thank you for updating your plugins. You are awesome.:)
I ran into a problem with the config. First I just pasted the two dlls into the plugins folder. No errors this time. however withouth the config, I could protect nothing. Then I copied the config to where it belongs, now I get this error, no idea why. I'm running an unstable of Tshock for Terraria 1.3.0.6.
I will test it out with an 1.3.0.5 version to see if this error will show up or not.

2015-07-22 18:13:17 - TShock: INFO: Welcome to TShock for Terraria. Initialization complete.
2015-07-22 18:13:25 - PluginTrace: ERROR: [Protector] Reading the configuration file failed. This plugin will be disabled. Exception details:
System.FormatException: Input string was not in a correct format.
   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   at Terraria.Plugins.CoderCow.Protector.Configuration.Read(String filePath)
   at Terraria.Plugins.CoderCow.Protector.ProtectorPlugin.InitConfig()
2015-07-22 18:13:25 - PluginTrace: ERROR: [Protector] THIS PLUGIN IS DISABLED, EVERYTHING IS UNPROTECTED!

**Comment by Tygra** [comment]
Sorry I didn't check the closed ticket first. Got my explanation. My bad.
