### ISSUE TITLE
forgotten null check?

### ISSUE THREAD

**Issue by Hiarni** [CoderCow/Protector-Plugin#36]
[Protector] Error: One PlayerSpawn event handler has thrown an unexpected exception. Exception details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Plugins.CoderCow.Protector.ProtectionManager.CheckProtectionAccess(ProtectionEntry protection, TSPlayer player, Boolean fullAccessRequired)
   at Terraria.Plugins.CoderCow.Protector.ProtectionManager.CheckBlockAccess(TSPlayer player, Point tileLocation, Boolean fullAccessRequired, ProtectionEntry& relatedProtection)
   at Terraria.Plugins.CoderCow.Protector.UserInteractionHandler.CheckProtected(TSPlayer player, Point tileLocation, Boolean fullAccessRequired)
   at Terraria.Plugins.CoderCow.Protector.UserInteractionHandler.HandlePlayerSpawn(TSPlayer player, Point spawnTileLocation)
   at Terraria.Plugins.CoderCow.Protector.ProtectorPlugin.Net_PlayerSpawn(Object sender, PlayerSpawnEventArgs e)
   at Terraria.Plugins.Common.Hooks.GetDataHookHandler.OnPlayerSpawn(PlayerSpawnEventArgs e)

**Comment by CoderCow** [comment]
Reopen if it still occurs.
