### ISSUE TITLE
New Bamboo build breaks this plugin.

### ISSUE THREAD

**Issue by TeeriaLLC** [CoderCow/Protector-Plugin#38]
https://i.gyazo.com/8b99670b3e42b34be5b749791a6a8933.png

As shown in the image above, since the TShock bamboo updated it kind of breaks some things..

**Comment by SmallSansSerif** [comment]
Yes got this error too on bamboo build #547 - http://direct.tshock.co:8085/browse/TERRA-TSHOCK/latest

[Protector] Reading a metadata file failed. Exception details:
System.MissingFieldException: Field 'Terraria.Tile.type' not found.
  at Terraria.Plugins.Common.MetadataHandlerBase.InitOrReadMetdata () [0x00000] in <filename unknown>:0 
[Protector] Failed initializing or reading metdata or its backup. This plugin will be disabled. Exception details:
System.MissingFieldException: Field 'Terraria.Tile.type' not found.
  at Terraria.Plugins.Common.MetadataHandlerBase.InitOrReadMetdata () [0x00000] in <filename unknown>:0 
  at Terraria.Plugins.CoderCow.Protector.ProtectorPlugin.InitWorldMetdataHandler () [0x00000] in <filename unknown>:0 
[Protector] THIS PLUGIN IS DISABLED, EVERYTHING IS UNPROTECTED!

**Comment by TeeriaLLC** [comment]
Yeah basically the new Bamboo build breaks every plugin containing
Main.Tile..

**Comment by SmallSansSerif** [comment]
Did your history plugin break too?

**Comment by SmallSansSerif** [comment]
So if it's recompiled against the new TSAPI then that should fix the problem according to @tylerjwatson

I guess they bumped the API a version up.

https://github.com/NyxStudios/TShock/issues/1111

**Comment by TeeriaLLC** [comment]
Please build this plugin with one of the newest Bamboo because when I tried it myself I keep getting this with even a fresh config file.

2015-09-13 14:50:51 - PluginTrace: ERROR: [Protector] Reading a metadata file failed. Exception details:
System.ArrayTypeMismatchException: Attempted to access an element as a type incompatible with the array.
   at Terraria.Plugins.CoderCow.Protector.WorldMetadata.Read(String filePath)
   at Terraria.Plugins.CoderCow.Protector.WorldMetadataHandler.ReadMetadataFromFile(String filePath)
   at Terraria.Plugins.Common.MetadataHandlerBase.InitOrReadMetdata()
2015-09-13 14:50:51 - PluginTrace: ERROR: [Protector] Failed initializing or reading metdata or its backup. This plugin will be disabled. Exception details:
System.ArrayTypeMismatchException: Attempted to access an element as a type incompatible with the array.
   at Terraria.Plugins.CoderCow.Protector.WorldMetadata.Read(String filePath)
   at Terraria.Plugins.CoderCow.Protector.WorldMetadataHandler.ReadMetadataFromFile(String filePath)
   at Terraria.Plugins.Common.MetadataHandlerBase.InitOrReadMetdata()
   at Terraria.Plugins.CoderCow.Protector.ProtectorPlugin.InitWorldMetdataHandler()
2015-09-13 14:50:51 - PluginTrace: ERROR: [Protector] THIS PLUGIN IS DISABLED, EVERYTHING IS UNPROTECTED!

**Comment by SmallSansSerif** [comment]
It already looks like he rebuilt for API 1.22 recently. Try to download the new build.

**Comment by TeeriaLLC** [comment]
I do not think that is for the newest bamboo build, I would test if the current bamboo weren't broken.

**Comment by CoderCow** [comment]
Should be fixed by Steal's commit.
