### ISSUE TITLE
ArrayTypeMismatchException

### ISSUE THREAD

**Issue by tanpro260196** [CoderCow/Protector-Plugin#52]
It throw an exception right after server start.
`2017-05-09 14:16:52 - PluginTrace: ERROR: [Protector] Reading a metadata file failed. Exception details:
System.ArrayTypeMismatchException: Attempted to access an element as a type incompatible with the array.
   at Terraria.Plugins.CoderCow.Protector.WorldMetadata.Read(String filePath)
   at Terraria.Plugins.CoderCow.Protector.WorldMetadataHandler.ReadMetadataFromFile(String filePath)
   at Terraria.Plugins.Common.MetadataHandlerBase.InitOrReadMetdata()
2017-05-09 14:16:52 - PluginTrace: ERROR: [Protector] Failed initializing or reading metdata or its backup. This plugin will be disabled. Exception details:
System.ArrayTypeMismatchException: Attempted to access an element as a type incompatible with the array.
   at Terraria.Plugins.CoderCow.Protector.WorldMetadata.Read(String filePath)
   at Terraria.Plugins.CoderCow.Protector.WorldMetadataHandler.ReadMetadataFromFile(String filePath)
   at Terraria.Plugins.Common.MetadataHandlerBase.InitOrReadMetdata()
   at Terraria.Plugins.CoderCow.Protector.ProtectorPlugin.InitWorldMetdataHandler()
2017-05-09 14:16:52 - PluginTrace: ERROR: [Protector] THIS PLUGIN IS DISABLED, EVERYTHING IS UNPROTECTED!`

**Comment by CoderCow** [comment]
See https://tshock.co/xf/index.php?threads/protector.5012/#post-48244
